graduate:
    type: rest
    resource: Gradually\RestBundle\Controller\GraduateController

cv:
    parent: graduate
    type: rest
    resource: Gradually\RestBundle\Controller\CvController

qualification:
    parent: cv
    type: rest
    resource: Gradually\RestBundle\Controller\QualificationController

experience:
    parent: cv
    type: rest
    resource: Gradually\RestBundle\Controller\ExperienceController

profile:
    parent: cv
    type: rest
    resource: Gradually\RestBundle\Controller\ProfileController