gradually_search:
    resource: "@GraduallySearchBundle/Controller/"
    type:     annotation
    prefix:   /search

gradually_home:
    resource: "@GraduallyHomeBundle/Controller/"
    type:     annotation
    prefix:   /

gradually_purchase:
    resource: "@GraduallyPurchaseBundle/Controller/"
    type:     annotation
    prefix:   /purchase

gradually_job:
    resource: "@GraduallyJobBundle/Controller/"
    type:     annotation

gradually_recruiter:
    resource: "@GraduallyRecruiterBundle/Controller/"
    type:     annotation
    prefix:   /recruiters

gradually_graduate:
    resource: "@GraduallyGraduateBundle/Controller/"
    type:     annotation
    prefix:   /graduates

gradually_user:
    resource: "@GraduallyUserBundle/Controller/"
    type:     annotation

gradually_admin:
    resource: "@GraduallyAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
