gradually_search:
    resource: "@GraduallySearchBundle/Controller/"
    type:     annotation
    prefix:   /search

gradually_home:
    resource: "@GraduallyHomeBundle/Controller/"
    type:     annotation
    prefix:   /

gradually_job:
    resource: "@GraduallyJobBundle/Controller/"
    type:     annotation

gradually_application:
    resource: "@GraduallyApplicationBundle/Controller/"
    type:     annotation

gradually_recruiter:
    resource: "@GraduallyRecruiterBundle/Controller/"
    type:     annotation
    prefix:   /recruiters

gradually_graduate:
    resource: "@GraduallyGraduateBundle/Controller/"
    type:     annotation
    prefix:   /graduates

gradually_user:
    resource: "@GraduallyUserBundle/Controller/"
    type:     annotation