gradually_job:
    resource: "@GraduallyJobBundle/Controller/"
    type:     annotation

gradually_rest:
    type: rest
    resource: "@GraduallyRestBundle/Resources/config/routing.yml"
    prefix:   /api

gradually_recruiter:
    resource: "@GraduallyRecruiterBundle/Controller/"
    type:     annotation
    prefix:   /recruiters

gradually_graduate:
    resource: "@GraduallyGraduateBundle/Controller/"
    type:     annotation
    prefix:   /graduates

gradually_user:
    resource: "@GraduallyUserBundle/Controller/"
    type:     annotation

gradually_admin:
    resource: "@GraduallyAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
