security:
    firewalls:
        admin_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: /user/login
                check_path: /user/login_check
                csrf_provider: form.csrf_provider

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER: ROLE_ADMIN

    access_control:
        - { path: ^/admin/, roles: ROLE_USER }
        - { path: ^/admin$, roles: ROLE_USER }

    providers:
        main:
            entity: { class: GraduallyUserBundle:User, property: username }

    encoders:
        Gradually\UserBundle\Entity\User: 
            algorithm: bcrypt
            cost: 12