security:
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: /user/login
                check_path: /user/login_check
                csrf_provider: form.csrf_provider
                username_parameter: _email
                password_parameter: _password
            logout:
                path: /user/logout
                target: /user/login

    role_hierarchy:
        ROLE_ADMIN: ROLE_NORMAL
        ROLE_SUPER: ROLE_ADMIN

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin$, roles: ROLE_ADMIN }

    providers:
        main:
            entity: { class: GraduallyUserBundle:User, property: email }

    encoders:
        Gradually\UserBundle\Entity\User: 
            algorithm: bcrypt
            cost: 12
