security:
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: /user/login
                check_path: /user/login_check
                csrf_provider: form.csrf_provider
            logout:
                path: /user/logout
                target: /user/login

    role_hierarchy:
        ROLE_ADMIN: [ROLE_RECRUITER, ROLE_GRADUATE]
        ROLE_SUPER: ROLE_ADMIN

    providers:
        main:
            entity: { class: GraduallyUtilBundle:User, property: username }

    encoders:
        Gradually\UtilBundle\Entity\User: 
            algorithm: bcrypt
            cost: 12
